### ISSUE TITLE
Facebook Login implementation?

### ISSUE THREAD

**Issue by ArcherEmiya05** [FirebaseExtended/auth-without-play-services#15]
I tried to add Facebook login but I am getting 400 error while body always return null. I tried to look on SO but I can't manage to get any error message from the response.

I tried it using Postman and it seems this is the response though still not sure.
```json
{
    "error": {
        "code": 400,
        "message": "INVALID_IDP_RESPONSE : Unsuccessful debug_token response from Facebook: {\"error\":{\"message\":\"(#100) The App_id in the input_token did not match the Viewing App\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"Ahw74pBnYOiiiL5o0FrlFDb\"}}",
        "errors": [
            {
                "message": "INVALID_IDP_RESPONSE : Unsuccessful debug_token response from Facebook: {\"error\":{\"message\":\"(#100) The App_id in the input_token did not match the Viewing App\",\"type\":\"OAuthException\",\"code\":100,\"fbtrace_id\":\"Ahw74pBnYOiiiL5o0FrlFDb\"}}",
                "domain": "global",
                "reason": "invalid"
            }
        ]
    }
}
```

Also how to get FIREBASE_ID_TOKEN as it seems needed first before logging in.
The flow for Facebook login are these:

-Click Facebook Login Button
-A window will show app asking for credentials if FB app is not installed. If installed and account is logged in with the app, only permission will show and no need credentials anymore.
-Facebook will generate a token
-Firebase will use the Facebook token along with Firebase ID Token from documentation here: https://firebase.google.com/docs/reference/rest/auth#section-link-with-oauth-credential
The problem is I do not have Firebase ID Token at that moment as I have not signed in yet with Firebase.

**Comment by samtstern** [comment]
A few things:

- The error message says `The App_id in the input_token did not match the Viewing App`.  If you Google that error message it seems to be that you're not providing the right App ID to Facebook or missing some other config.  It's not an issue with Firebase that I can see.
- The [method you linked](https://firebase.google.com/docs/reference/rest/auth#section-link-with-oauth-credential) is for adding a Facebook credential to an *existing* Firebase Authentication user, not creating a new user from a Facebook credential.  That's why you need the Firebase ID Token, because you must already be signed in to link.  To do a basic Facebook sign in you want to use [this method](https://firebase.google.com/docs/reference/rest/auth#section-sign-in-with-oauth-credential)

Overall this question is out of scope for this repo so I am going to close it, but I hope that helps!
